name: Deploy to Amazon

on:
  push:
    branches: ["main", "dev"]

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up env file
        run: |
          touch .env
          echo NEXT_PUBLIC_TESTE=Testando
          cat .env

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.14.0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy to S3
        run: aws s3 sync ./out s3://${ENVIRONMENT}-webapp-deltastroke

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
