name: Deploy to Amazon

permissions:
  contents: read # This is required for actions/checkout
  id-token: write # This is required for requesting the JWT

on: push

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }} # Env vars won't work here
  cancel-in-progress: false

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build
        env:
          NEXT_PUBLIC_API_ENDPOINT: https://3l03puaz4j.execute-api.sa-east-1.amazonaws.com/dev
          NEXT_PUBLIC_WS_ENDPOINT: wss://i2751iwn1e.execute-api.us-east-1.amazonaws.com/production
        run: |
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::783764600983:role/github-webapp-deploy-role
          aws-region: sa-east-1

      - name: Deploy to S3
        run: aws s3 sync ./out s3://${ENVIRONMENT}-webapp-deltainstituto --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ env.ENVIRONMENT == 'prd' && secrets.PRD_CLOUDFRONT_DISTRIBUTION_ID || secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
